#!/usr/bin/env bash
# Read-only status of the BandRoom stack. Run ON THE SERVER, in the application directory
# (e.g. /opt/bandroom); it never changes files, containers or the database:
#
#   sudo ./status.sh                    versions, containers, health, disk, backups, recent warnings
#   sudo ./status.sh song "<title>"     tracks, versions and audio variants of songs whose title
#                                       contains <title> (case-insensitive, deleted ones included)
#   sudo ./status.sh uploads [hours]    audio uploaded in the last <hours> (default 24)
#   sudo ./status.sh --help
#
# Environment (only with full sudo rights): BANDROOM_BACKUP_DIR=<dir>, as for deploy.sh.
set -euo pipefail

say() { printf '==> %s\n' "$*"; }
info() { printf '    %s\n' "$*"; }
die() {
  printf 'ERROR: %s\n' "$*" >&2
  exit 1
}

usage() {
  sed -n '3,9p' "$0" | sed 's/^# \{0,1\}//'
}

version_of_image() {
  local v
  v="$(docker image inspect -f '{{range .Config.Env}}{{println .}}{{end}}' "$1" 2>/dev/null |
    sed -n 's/^APP_VERSION=//p' | head -n 1)"
  if [ -z "$v" ]; then
    v="$(docker image inspect -f '{{.Id}}' "$1" 2>/dev/null | sed 's/^sha256://' | cut -c1-12)"
  fi
  printf '%s' "${v:-unknown}"
}

overview() {
  local svc c state health version line
  say "BandRoom status in $APP_DIR ($(date -u '+%Y-%m-%d %H:%M:%S UTC'))"
  line="$(grep -E '^BANDROOM_TAG=' .env 2>/dev/null | tail -n 1 || true)"
  info ".env: ${line:-no BANDROOM_TAG (latest)}"

  say "Containers"
  for svc in app worker caddy; do
    c="$(docker compose ps -a -q "$svc" 2>/dev/null | head -n 1 || true)"
    if [ -z "$c" ]; then
      info "$svc: no container"
      continue
    fi
    state="$(docker inspect -f '{{.State.Status}} since {{.State.StartedAt}}' "$c" 2>/dev/null || echo unknown)"
    health="$(docker inspect -f '{{if .State.Health}}{{.State.Health.Status}}{{else}}no health check{{end}}' "$c" 2>/dev/null || echo unknown)"
    if [ "$svc" = caddy ]; then
      version="$(docker inspect -f '{{.Config.Image}}' "$c" 2>/dev/null || echo unknown)"
    else
      version="$(version_of_image "$(docker inspect -f '{{.Image}}' "$c")")"
    fi
    info "$svc: $version, $state, $health"
  done

  say "Disk"
  df -h "$APP_DIR/data" "$BACKUP_DIR" 2>/dev/null | awk '!seen[$0]++' | sed 's/^/    /' ||
    info "(df failed)"
  if [ -d "$APP_DIR/data" ]; then
    info "data/: $(du -sh "$APP_DIR/data" 2>/dev/null | cut -f1)"
  fi

  say "Backups in $BACKUP_DIR (newest 10)"
  if [ -d "$BACKUP_DIR" ]; then
    # Names are generated by deploy.sh (no spaces); newest first by modification time.
    # shellcheck disable=SC2010,SC2012
    ls -1t "$BACKUP_DIR" 2>/dev/null | grep -E '\.sqlite$' | head -n 10 | while read -r f; do
      info "$(du -h "$BACKUP_DIR/$f" | cut -f1)	$f"
    done || true
    info "total: $(find "$BACKUP_DIR" -maxdepth 1 -name '*.sqlite' | wc -l | tr -d ' ') backups," \
      "$(du -sh "$BACKUP_DIR" | cut -f1)"
  else
    info "(no backup directory)"
  fi

  say "Recent warnings and errors (app, worker; last 50)"
  # pino levels: 40 warn, 50 error, 60 fatal.
  docker compose logs --no-color --tail 2000 app worker 2>&1 |
    grep -E -i '"level":(40|50|60)|warn|error|fatal' | tail -n 50 | sed 's/^/    /' ||
    info "(none)"
}

# Runs a read-only query script inside the app container. The user's argument travels only as an
# environment variable (one argv element for docker, a bound SQL parameter for the query): it is
# never part of a shell command line or of the SQL text.
run_query() {
  local mode="$1" arg="$2"
  docker compose exec -T -w /app/apps/server -e "BR_MODE=$mode" -e "BR_ARG=$arg" app \
    node --input-type=commonjs - <<'JS'
const Database = require("better-sqlite3");
const db = new Database(`${process.env.DATA_DIR || "/data"}/bandroom.sqlite`, {
  readonly: true,
  fileMustExist: true,
});
const mode = process.env.BR_MODE;
const arg = process.env.BR_ARG ?? "";
const iso = (ms) => (ms == null ? "" : new Date(ms).toISOString().replace(/\.\d+Z$/, "Z"));
const json = (s) => {
  try {
    return s ? JSON.parse(s) : {};
  } catch {
    return {};
  }
};
const variantsOf = db.prepare(
  "SELECT variant, meta FROM asset_variants WHERE asset_id = ? AND variant NOT LIKE 'seekindex%' ORDER BY variant",
);
const assetLine = (a) => {
  const probe = json(a.probe);
  const variants = variantsOf.all(a.asset_id).map((v) => {
    if (v.variant !== "opus") return v.variant;
    const m = json(v.meta);
    return `opus(${m.bitrate ?? "?"} kbps, ${m.channels ?? "?"} ch)`;
  });
  return [
    `asset ${a.asset_id} ${a.status}`,
    `codec ${probe.codec ?? "?"}${probe.lossless ? " lossless" : " lossy"}`,
    `variants: ${variants.join(", ") || "none"}`,
    `ingest options: ${a.ingest_options ?? "default"}`,
  ].join("; ");
};

if (mode === "song") {
  const songs = db
    .prepare(
      `SELECT s.id, s.title, s.deleted_at, p.name AS project, p.deleted_at AS project_deleted_at
         FROM songs s JOIN projects p ON p.id = s.project_id
        WHERE instr(lower(s.title), lower(?)) > 0
        ORDER BY p.name, s.title LIMIT 20`,
    )
    .all(arg);
  if (songs.length === 0) console.log("No song title contains that text.");
  const versions = db.prepare(
    `SELECT t.name AS track, t.deleted_at AS track_deleted_at, t.current_version_id,
            v.id AS version_id, v.number, v.label, v.deleted_at, v.archived_at, v.archived_reason,
            a.id AS asset_id, a.status, a.original_filename, a.probe, a.ingest_options
       FROM tracks t
       JOIN track_versions v ON v.track_id = t.id
       JOIN assets a ON a.id = v.asset_id
      WHERE t.song_id = ?
      ORDER BY t.sort_order, t.name, v.number`,
  );
  for (const s of songs) {
    const del = s.deleted_at ? ` [deleted ${iso(s.deleted_at)}]` : "";
    const pdel = s.project_deleted_at ? " [project deleted]" : "";
    console.log(`\n${s.project}${pdel} / ${s.title}${del} (song ${s.id})`);
    let lastTrack = null;
    for (const v of versions.all(s.id)) {
      if (v.track !== lastTrack) {
        const tdel = v.track_deleted_at ? ` [deleted ${iso(v.track_deleted_at)}]` : "";
        console.log(`  track "${v.track}"${tdel}`);
        lastTrack = v.track;
      }
      const flags = [
        v.version_id === v.current_version_id ? "current" : "",
        v.deleted_at ? `deleted ${iso(v.deleted_at)}` : "",
        v.archived_at ? `archived ${iso(v.archived_at)} (${v.archived_reason ?? "removed"})` : "",
      ].filter(Boolean);
      console.log(
        `    v${v.number}${v.label ? ` "${v.label}"` : ""} ${v.original_filename}` +
          `${flags.length ? ` [${flags.join(", ")}]` : ""}`,
      );
      console.log(`      ${assetLine(v)}`);
    }
  }
} else if (mode === "uploads") {
  const since = Date.now() - Number(arg) * 3600 * 1000;
  const rows = db
    .prepare(
      `SELECT a.id AS asset_id, a.created_at, a.status, a.error, a.original_filename, a.size_bytes,
              a.probe, a.ingest_options, u.username,
              (SELECT p.name || ' / ' || s.title || ' / ' || t.name || ' v' || v.number
                 FROM track_versions v JOIN tracks t ON t.id = v.track_id
                 JOIN songs s ON s.id = t.song_id JOIN projects p ON p.id = s.project_id
                WHERE v.asset_id = a.id LIMIT 1) AS used_in
         FROM assets a LEFT JOIN users u ON u.id = a.uploaded_by
        WHERE a.kind = 'audio' AND a.created_at >= ?
        ORDER BY a.created_at DESC LIMIT 200`,
    )
    .all(since);
  console.log(`${rows.length} audio upload(s) since ${iso(since)}`);
  for (const a of rows) {
    const mb = (a.size_bytes / 1048576).toFixed(1);
    console.log(
      `\n${iso(a.created_at)} ${a.username ?? "?"} ${a.original_filename} (${mb} MB)` +
        `${a.used_in ? ` -> ${a.used_in}` : " (not in a track)"}`,
    );
    console.log(`  ${assetLine(a)}${a.error ? `; error: ${a.error}` : ""}`);
  }
}
JS
}

main() {
  local cmd="${1:-}"
  case "$cmd" in
    -h | --help)
      usage
      exit 0
      ;;
    "")
      if [ "$#" -gt 0 ]; then die "Empty command."; fi
      ;;
    song)
      if [ "$#" -ne 2 ]; then die 'Usage: sudo ./status.sh song "<title fragment>"'; fi
      if [ -z "$2" ] || [ "${#2}" -gt 200 ]; then die "The title fragment must be 1-200 characters."; fi
      if [[ $2 == *[[:cntrl:]]* ]]; then die "The title fragment must not contain control characters."; fi
      ;;
    uploads)
      if [ "$#" -gt 2 ]; then die "Usage: sudo ./status.sh uploads [hours]"; fi
      if [ "$#" -eq 2 ] && ! [[ $2 =~ ^[1-9][0-9]{0,4}$ ]]; then
        die "hours must be a whole number from 1 to 99999, got '$2'."
      fi
      ;;
    *)
      usage >&2
      die "Unknown command '$cmd'."
      ;;
  esac

  cd "$(dirname "$0")"
  APP_DIR="$(pwd -P)"
  BACKUP_DIR="$(realpath -m "${BANDROOM_BACKUP_DIR:-$APP_DIR/../bandroom-backup}")"

  case "$cmd" in
    "") overview ;;
    song)
      say "Songs whose title contains: $2"
      run_query song "$2"
      ;;
    uploads)
      say "Audio uploads in the last ${2:-24} h"
      run_query uploads "${2:-24}"
      ;;
  esac
}

main "$@"
